### ISSUE TITLE
Formalise distinction between authors and contributors, update on website

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#1941]
### Background Information

At the moment, we are ambiguous about what defines an author and what defines a contributor. I propose the following definitions: 

- **authors**: those who have made _significant_ contributions to the package within the last year (significant at the discretion of the maintainer).
- **contributors**: those who have made smaller contributions in the last year, or who have not made contributions for longer than a year.

This would be re-evaluated and updated at every release.

We could then display only authors in the sidebar, while keeping authors and contributors in the `authors.html` page by adding the following in `_pkgdown.yml`:

```
authors:
  footer:
    roles: [aut, ctb, cre, fnd]
    text: "Developed by"
  sidebar:
    roles: [aut]
  before: "This package is proudly brought to you by:"
  after: "<our definition of what it means to be an author/contributor>"
```

Note that, as shown above, we could then be fully transparent about these definitions by recording it in the "after" argument.

@pharmaverse/admiral what do you think?

### Definition of Done

Clarified strategy for authors/contributors and pkgdown website updated to reflect this.
