### ISSUE TITLE
Validation report workflow failed

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#719]
@epijim The [workflow ](https://github.com/Roche-GSK/admiral/runs/4381685990?check_suite_focus=true) fails in the "Build report" step 🙁 

```
Run insightsengineering/r-pkg-validation@main
Run echo "::set-output name=R_VERSION::$(R --version | head -1 | awk '{print $3}')"
Run mkdir -p ${RUNNER_TEMP}/Library
.libPaths(c('/home/runner/work/_temp/Library', .libPaths()))
Run echo "::set-output name=TEX_LIVE_VERSION::$(tlmgr --version |tail -1 |awk '{print $NF}')"
/home/runner/work/_temp/470de5f3-cbb7-4f0e-b9d0-8fff2485b8f0.sh: line 1: tlmgr: command not found
Run actions/cache@v2
Cache not found for input keys: v1-Linux-4.1.2-1ff75943a0885e964ac47bf0809a096d5aca5efa72a5f86a2a93bb9e261120d5, v1-Linux-4.1.2
Run actions/cache@v2
Cache not found for input keys: v1-Linux--, v1-Linux-
Run ${GITHUB_ACTION_PATH}/dependencies.R
Error in loadNamespace(x) : there is no package called ‘remotes’
Calls: lapply ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Error: Process completed with exit code 1.
```

**Comment by thomas-neitmann** [comment]
I also noted that in the workflow yml file the file name is specified with an underscore on time and a dash the other time.

```
        with:
          file: ./validation_report.pdf
          asset_name: validation-report.pdf
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: false
```

**Comment by epijim** [comment]
ahh - sorry, I thought I made a PR to change this line:

https://github.com/Roche-GSK/admiral/blob/devel/.github/workflows/r-pkg-validation.yml#L23

(it should point at a version, not main). I'll double check with Konrad.

**Comment by epijim** [comment]
I think it needs to be:

`uses: insightsengineering/thevalidatoR@v1.0`

```yaml
---
name: R Package Validation report

on: # Run this action when a release is published
  release:
    types: [published]

jobs:
  r-pkg-validation:
    name: Create report 📃
    runs-on: ubuntu-latest
    # Set Github token permissions
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: write
      deployments: write
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v2

      - name: Build report 🏗
        uses: insightsengineering/thevalidatoR@v1.0

      # Upload the validation report to the release
      - name: Upload report to release 🔼
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./validation_report.pdf
          asset_name: validation-report.pdf
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: false
```
